RunestoneInteractive/RunestoneServer

overview/overview.rst
=> Fix incorrect program output

pythonds/source/Graphs/BuildingtheKnightsTourGraph.rst
Refactored the method per our discussion.
=> Improved posToNodeId method

controllers/mygroup.py, views/mygroup/manageGroup.html, views/mygroup/schedule.html
- fixed the repeated first name on the group member list.
- fixed an exception that happens comparing a date type to a datetime type in the schedule view when plan end date is less than the current date.
- fixed the Continue Studying link under each chapter plan to go to the right book. It was hard coded to thinkcsp. 
- cleaned up some querying and added some checks that the user is logged in on mygroup methods.
- I added some filler text on how to get started if nothing is scheduled. right now it is a blank page when you first create a group.
=> small group improvements

controllers/default.py
@presnick -- This is another way to prevent problems with users changing usernames.   Once the username is set, it cannot be changed.
=> keep user from changing their username

views/default/user.html, views/groupLayout.html, views/layout.html
Proposed changes to runestoneinteractive.org (the overview, etc) upcoming.
=> Changes (as discussed) to home page of InteractivePython.org

controllers/admin.py, views/admin/assignments.html
=> Make base course search criteria for q bank

views/admin/admin.html
This simply changes which function the rebuild form maps to in the controller.
=> Updated rebuild form

controllers/admin.py, static/js/admin.js, views/admin/grading.html
Updated the grading interface so the right side supports more than just activecode questions.
=> Updated right side of grading tab

controllers/admin.py, static/js/admin.js, views/admin/assignments.html, views/admin/grading.html
This should fix a number of issues. 
1. Grading interface should correctly pull in the students code now. 
2. The grading interface now only shows summative questions. 
3. Tried to speed up the function to search for questions by making better use of the database. 
4. Removed the dropdown for summative, formative, external on the right hand side of the assignments tab. Now when you add a question it will be added to whatever tab you have selected on the left hand side. 
5. Added buttons to change the duedate and description for an assignment.
=> Updates and a handful of bug fixes to instructors interface

controllers/admin.py, static/js/admin.js, views/admin/admin.html
1. Added a datepicker plugin for the admin rebuild form
2. In the grading interface, the code table now stores the activecode/actex divid instead of the question divid.
=> Fix issue 825 for admin rebuild and store divid for activecode

controllers/default.py, views/default/reportabug.html
Added a JavaScript function to ensure that relevant fields are filled in.
=> added check to ensure filled entries

models/grouped_assignments.py
The issue became that the db could return a None or null value for an assignment score and would result in summing an int and NoneType down the line.  Adding a try/except catches datatype errors and replaces them with 0s.
=> Protected against adding an int and None

README.rst, models/0.py
Update README.rst, plus a minor patch in 0.py, for Windows.
=> Fixes for Windows

controllers/dashboard.py, models/db_dashboard.py, models/db_ebook.py, static/js/admin.js, views/dashboard/index.html, views/dashboard/studentreport.html
Also fixed a minor spelling error when creating new questions for assignments.
=> Added Functionality for Assignment Table in "studentreport" View

controllers/dashboard.py, static/dashboard.css, views/dashboard/index.html
I overlooked an issue with linking the chapter subtitles to their proper html pages. The issue is resolved now.
=> Fixed bug where Chapter Titles would sometimes not link to proper pages

models/scheduler.py
...for that poor, little single-tasking origins of Windows...since it can't delete files that are open...
=> Fix: Error on Windows during a scheduled build.

static/js/admin.js
=> Fix: Clear readings table when loading an assignment.

static/js/admin.js
=> Sort student names on grading page

CONTRIBUTING.md
=> Test jenkins build of PR's

CONTRIBUTING.md
Trying to set up Travis CI for PR's
=> Travis-CI for a Pull Reqest

controllers/assignments.py, rsmanage/makeuser.py, rsmanage/rsmanager.py
=> Upstream updates

tests/test_admin.py
=> tests added for _get_question_id and sections_list in admin.py

controllers/assignments.py
See https://github.com/RunestoneInteractive/RunestoneServer/issues/1093.
=> Fix: Avoid invalid useinfo_id.

.travis.yml, modules/rs_grading.py, tests/make_clean_db_with_grades.py, tests/run_tests.py, tests/test_admin.py
I noticed that `run_test.py --rebuildgrades` failed; this fixes it.
=> Fix: Get make_clean_db_with_grades.py working again.

static/js/admin.js
This is really just about a small refactoring of how the questions table is constructed.
A somewhat sad side effect is that my refactoring tool decided to reformat the js file according to some guidelines that makes it look like I changed a lot more than I did.   Its nice to be consistent but these kinds of changes cause ripple annoying merge conflicts sometimes.
=> major performance update to creating question table

controllers/admin.py, modules/rs_grading.py, static/js/admin.js, views/admin/grading.html
I found that certain characters in the names of assignments were causing the grading interface to appear unresponsive.  The problem stems from how we embed data into the DOM for later use by the javascript interface elements.
In the long run I think it would be better to get most of this data by API request when we need it.  But in the short term this is a better solution and will avoid JSON parse errors.
=> Fix problems with odd characters in assignment names

README.rst, private/README.rst
Tried installing. These things helped.
Also I had to make sure pip was new enough, otherwise it errored out.
=> tweaks for install

controllers/admin.py, controllers/ajax.py, controllers/coach.py, controllers/lti.py, models/db.py, models/db_sections.py, rsmanage/rsmanager.py, scripts/cleanup_courses.py, scripts/createMchoiceGrades.py, scripts/find_modified_index.py, scripts/minifyjs.py, scripts/populateDivTable.py, scripts/pparse.py, scripts/split.py, scripts/uwsgi_mem.py
- Avoid calling `db.commit()` during an Ajax callback. This makes testing difficult (the database is modified unnecessarily.)
- Remove some `print` statements that produce noise in testing.
- Call `print` as a function, to prepare for porting to Python 3.
=> Misc updates

models/db.py, views/default/user.html
**Background:** I use Runestone to give tests in my course. I use two-factor authentication, where only test proctors have the second password, to ensure that students can't log in from home to take the test. 
This PR adds the possibility to using two-factor authentication (but doesn't enable it without uncommenting two lines in `db.py`).
=> Add: Capability to use two-factor authentication.

controllers/ajax.py, controllers/default.py, scripts/build_preview.sh, tests/test_server.py
This PR fixes several bugs and weaknesses in the `ajax/preview_question` endpoint:
- It now works with Unicode.
- It doesn't produce internal server errors on bad params.
- It works on Window, Linux, and Mac.
There are also a few minor improvements to the test bench.
=> preview_question endpoint fixes

.travis.yml, tests/test_server.py, views/assignments/practice.html, views/assignments/practiceNotStartedYet.html, views/default/privacy.html, views/default/terms.html, views/default/user.html
This PR builds on #1160 by explicitly specifying which version of web2py to use for testing.
=> Define web2py version for testing

modules/rs_grading.py
This might have thrown people off at a later time if they are trying to refactor the grading code or interface, so fixing the comment.
=> fix confusing comment about data type of sid in grading code

controllers/ajax.py, controllers/default.py, models/0.py, models/db.py, models/questions.py, modules/feedback.py, modules/rs_grading.py, tests/test_ajax.py, tests/test_server.py
This PR allows grading of fill-in-the-blank questions on the server. However, server-side grading only occurs when a course is built with server-side grading enabled. Therefore, current behavior (client-side grading) will be maintained until a RunestoneComponents PR provides the necessary updates.
Merge #1168 before this.
=> Server side fitb

requirements-test.txt, tests/test_ajax.py
This is a simple PR that adds much more testing for the server-side fill-in-the-blanks question type. The tests demonstrate that grading works properly on the server.
=> Add: Server-side tests of fitb.

controllers/assignments.py, views/assignments/doAssignment.html
If no points for that chapter, don't show points earned line
Show full chapter and subchapter name rather than the compressed labels.
=> better display of readings in reading assignments

controllers/lti.py
Clean: 
- Remove unused variables, or unnecessary declarations of variables.
- Simplify control flow (no else after a return).
Fix:
- Use the provided URL unless ``settings.lti_uri`` is defined.
=> LTI cleanup

views/assignments/doAssignment.html
Bug introduced recently that may affect any teachers who create ungraded assignments.
=> URGENT; fix bug when there are 0 points for the assignment

tests/test_assignments.py
I don't know why I didn't see this missing import before.
=> Fix broken test.

controllers/appadmin.py, views/appadmin.html
This provides an updated (and Python 3-compatible) appadmin interface.
=> Update: Copied from the welcome app, web2py 2.18.2.

views/default/user.html
Showing login on the homepage when a user is already logged in is confusing.  This cleans that up.
=> Cleanup home

.dockerignore, .gitignore, controllers/admin.py, controllers/dashboard.py, controllers/default.py, docker/entrypoint.sh, docker/uwsgi/sites/runestone.ini, static/js/admin.js, tests/test_server.py
* Removing cruft from admin.py 
* using POST with an XMLHttpRequest object causes the server to fail in 3.7 -- convert to jQuery.post
* Write some new style cases for admin !! @bjones1 I actually got a pytest test to work!
=> Clean admin

controllers/admin.py, controllers/ajax.py, models/db.py, models/db_ebook.py, models/scheduler.py, modules/feedback.py, modules/rs_grading.py, requirements-test.txt, tests/test_course_1/_sources/index.rst, tests/test_course_1/_sources/lp_demo-test.py, tests/test_course_1/_sources/lp_demo.py, tests/test_course_1/conf.py, tests/test_course_1/pavement.py, tests/test_server.py
This is the server side for https://github.com/RunestoneInteractive/RunestoneComponents/pull/817. It won't pass until that PR is merged.
=> Add: Server-side support for literate programming question types.

controllers/assignments.py, controllers/dashboard.py, modules/outcome_request.py, modules/outcome_response.py
Clean up a few missing/extra imports.
=> Misc fixes

models/db.py, models/db_dashboard.py, models/db_ebook.py, models/db_ebook_chapters.py, models/db_sections.py, models/grouped_assignments.py, models/questions.py, rsmanage/rsmanager.py
@bjones -- this completes some cleanup on the test migrations PR.  The migration prefixes need to be used all or nothing or else it is chaos as you switch back and forth between different configurations.  Once I ran the tests, everything was messed up in the development or production environments.  Travis tests were passing because it was a clean environment and we only ran tests.  This should restore order.
At least it does in a clean and not-so clean Docker environment.  Now we'll let travis have a say.
=> Test migrate fixes

.travis.yml, controllers/admin.py, scripts/dtest, tests/.coveragerc, tests/conftest.py, tests/run_tests.py, tests/test_admin.py, tests/test_course_1/_sources/test_chapter_1/subchapter_b.rst, tests/test_server.py
Create a simple fixture that allows the tester to easily create an assignment, add questions, autograde, calculate totals set deadlines, etc.
Builds on work in #1257
=> Add test_assignment fixture and simple test

controllers/books.py, tests/conftest.py, tests/test_admin.py, tests/test_ajax2.py, tests/test_autograder.py, tests/test_dashboard.py, tests/test_server.py
There were several test holes in the coverage, resulting in several exceptions. This PR fixes the exceptions and adds testing, bringing coverage to 86%.
It also correct an incorrect approach in the test framework -- a _TestUser now stores the course object, not just the course name. This results in lots of changes to all the test code to incorporate this.
=> Fix: Correct dynamic routing.

controllers/admin.py, controllers/dashboard.py
…so that the tabs can be more easily distinguished.
=> Added titles to some of the instructor's pages

controllers/admin.py, controllers/assignments.py, static/js/selfgrade.js, views/admin/assignments.html, views/assignments/doAssignment.html
This addresses the conversation on slack around letting students self grade their assignments.
Notes:
1.  Deadlines are not enforced
2. Instructors should make sure that they pay attention to the grading options for problems that cannot be autograded to make sure they are set to manual.
3. Once the instructor has released the grades for an assignment then self grading is turned off
@presnick This uses a bit of the code that you had in place for coursera, but it was incomplete.
=> Self grade

tests/README.rst, tests/conftest.py
Just a few more hints in the documentation.
=> Documentation update

controllers/dashboard.py
This prevents exceptions when looking at the gradebook.
BUT, it should be accompanied with tests that show the failures. Would you have time to work on this, given you've written some autograder tests (and this is hopefully similar)? Hence the draft status -- while this code works, it should have tests.
=> Fix: Correct dashboard exceptions.

controllers/admin.py, controllers/assignments.py, models/grouped_assignments.py, modules/rs_grading.py, rsmanage/grade.py, static/js/admin.js, static/js/selfgrade.js, tests/conftest.py, tests/test_autograder.py, tests/utils.py, views/_sphinx_static_files.html, views/admin/grading.html
This generalizes the student_autograde function so that, in coursera_mode, it will submit the student's grade.
A test is included for the student_autograde function! @bjones1 may want to turn my writing of a models/.py file into a fixture.
There is also some small refactoring of the autograding and calc_totals code. Some of this was necessary because some calls are passing in student id as a DB row number and some are passing in a string, which requires lookups in different columns in the DB. After many confusions and duplications, I finally decided to just make a single function _get_students that would accept either one.
=> Fix self grade

controllers/admin.py, static/js/admin.js
- Present grading tab problems based on their ordering in an assignment.
- Avoid restoring incorrect data to a problem in the grading tab.
=> Correct ordering and display of problems in the grading tab

controllers/admin.py, static/js/admin.js, tests/test_admin.py, views/admin/admin.html
Many instructors have asked for the ability to copy an assignment from a previous course to their current course.  This PR adds that.
- Maybe when course is created 
- Maybe from the assignments tab
=> Add copy assignment(s) Feature

tests/conftest.py, tests/test_ajax2.py, tests/test_autograder.py, tests/test_designer.py, tests/test_server.py
There are still three test failures. I don't know enough about these tests to correct it. @bnmnetp and @psmaker, help please!
This is an implementation of https://github.com/RunestoneInteractive/RunestoneServer/issues/1283#issuecomment-516456420.
=> Fix: By default, test on a child course instead of a base course.

controllers/ajax.py
This came up while debugging changes on the server.
=> Fix: Ensure subprocess output is text.

.travis.yml, requirements-test.txt, tests/conftest.py, views/default/privacy.html, views/default/terms.html
replace calling the w3 service with running the validation locally.
- a bit ugly since everything that uses the w3 validator (vnu.jar) requires java!
- Errors are captured on stdout
=> Run Validation locally

modules/feedback.py
Merge this after merging https://github.com/RunestoneInteractive/RunestoneComponents/pull/890.
=> Fix: Update location of lp_common_lib.

.flake8, controllers/admin.py, controllers/ajax.py, controllers/appadmin.py, controllers/assignments.py, controllers/default.py, controllers/designer.py, controllers/proxy.py, controllers/sections.py, models/db.py, models/db_ebook_chapters.py, models/db_sections.py, models/scheduler.py, requirements-test.txt, tests/test_formatting.py, tests/test_server.py
* only for controllers and models so far.
* One big note -- flake8 wants you to use is None and is True in many places, but these CAN NOT be used inside a DAL query.
=> Flake8 fixes and tests

.travis.yml, Dockerfile, requirements-test.txt, tests/conftest.py, tests/test_server.py, views/default/user.html
This paves to way for lots of good JS in broswer/server-side interaction tests.
=> Add: A basic Selenium test.

tests/conftest.py
Found while doing Docker testing (from the wrong directory).
=> Fix: Make exception work on Linux.

controllers/admin.py, static/js/admin.js, views/admin/assignments.html
This fixes a long standing issue with the assignment builder adding chapters in a seemingly random order.
=> Fix reading order

.travis.yml, controllers/ajax.py, scripts/dtest, tests/conftest.py, tests/test_formatting.py
Fix: Restore DBURL after changing it.
=> Clean: Run tests from web2py directory.

controllers/admin.py, models/grouped_assignments.py, static/js/admin.js, views/admin/assignments.html, views/admin/grading.html, views/admin/practice.html, views/assignments/doAssignment.html
Create a quiz or exam the same way you create an assignment!  Add questions and then check the box on the assignment to wrap it up as a timed assessment.
=> turn an assignment into a quiz or exam !

controllers/admin.py, controllers/ajax.py, controllers/assignments.py, models/0.py, models/db.py, models/grouped_assignments.py, rsmanage/makeuser.py, static/js/admin.js, static/runestone-custom-sphinx-bootstrap.css, views/_sphinx_static_files.html, views/admin/admin.html, views/admin/assignments.html, views/admin/grading.html, views/assignments/doAssignment.html, views/layout.html
Collection of small fixes for instructor interface.
1. Add chapter/sub chapter numbers to question picker
2. Move the Release Grades button
3. Avoid duplicate assignment questions in old courses
4. add "version" information to js/css files to avoid stale cache while in development AND production.
5. Add time limit input for timed assignments
6. Add upload CSV file to register students for a class
7. Add password reset for instructors.
8. Make the navbar menus consistent across all pages
**Note** The production solution for #4 requires an update to 0.py when a new runestone components is released.  it could be automated by running runestone --version, but that would add overhead to EVERY page load.  And this is just as easy as rebuilding  `_sphinx_static_files.html` every release.
=> Instructor fixes

tests/test_admin.py
See https://github.com/RunestoneInteractive/RunestoneServer/issues/1259
Running tests:
```
$ scripts/dtest -k test_get_assignment_release_states
$ scripts/dtest -k test_delete_assignment_question
$ scripts/dtest -k test_reorder_assignment_questions
```
=> Add new tests in test_admin.py

controllers/designer.py, models/db.py, views/designer/index.html
Having the course level in a standardized way will help us to classify questions going forward.
=> collect course level

models/grouped_assignments.py, modules/rs_grading.py
This is a first step towards the assignment table, which needs to be able to find which row was graded then display that to the user.
=> Fix: Record id of graded row.

controllers/admin.py
When a student is removed from a course they are no longer moved into the base course if they are already enrolled in it. Thus, this prevents duplicate courses showing up in the Courses page after removing students from classes. The existing functionality of moving a student into the base course if they are **not** enrolled in it still holds true. So, in the case that a student is removed from a course, but they are not enrolled in the base course, they will be moved into that course.
=> fix(1327): No longer duplicates enrollment

controllers/designer.py, models/db_ebook.py, views/designer/index.html
Simple way for instructors to request an invoice.
=> add invoice request

views/dashboard/grades.html
In the Grading panel (gradebook), you can currently only filter by first name. However, this pull request adds the functionality to sort by last name as well as first name.
=> Patched issue #1292

controllers/admin.py, static/js/admin.js, views/admin/admin.html
Per many requests, you can now copy a single assignment.
=> Copy one assignment

controllers/dashboard.py, modules/db_dashboard.py, static/js/admin.js, views/dashboard/index.html
Add option to show activity for the last 24 hours.
=> Add option for daily activity

controllers/dashboard.py, views/admin/admin.html, views/dashboard/active.html
With many classes being forced into online mode, this report got the most requests.
=> Online students

tests/test_dashboard.py
See https://github.com/RunestoneInteractive/RunestoneServer/issues/1259
Running tests:
```
$ scripts/dtest -k test_grades
$ scripts/dtest -k test_questiongrades_redirect
$ scripts/dtest -k test_questiongrades
```
=> Add dashboard unit tests

views/layout.html
Noticed the year in the footer was a bit dated 😅 
I'm not familiar with web2py but the following search helped clear things up: https://github.com/web2py/web2py/search?l=HTML&q=year
=> Update copyright year in footer

modules/questions_report.py, static/js/assignment_table.js, tests/conftest.py, tests/test_server.py
Better error reporting per #1470.
=> Fix: Provide an error report when the assignment table raises an exception

modules/questions_report.py, static/js/assignment_table.js, tests/conftest.py, tests/test_server.py
Reverts RunestoneInteractive/RunestoneServer#1472
=> Revert "Fix: Provide an error report when the assignment table raises an exception"

modules/questions_report.py, static/js/assignment_table.js, tests/conftest.py, tests/test_server.py
This is a second attempt to fix the question table (the first was in #1472), but with a much lower anticipated performance impact. It includes:
- A fix in the JS to report exceptions to the user if these occur.
- A test case which shows the missing case and fails using the current code.
- A fix which makes the test case pass, but with a very minimal change to the query.
=> Question table fixes

modules/scheduled_builder.py
This pairs with https://github.com/RunestoneInteractive/RunestoneComponents/pull/1028 to improve a few LP things.
=> Add: Verification check to build.

controllers/books.py, controllers/lti.py, docker/README.md, docker/nginx/sites-available/runestone, models/db.py, views/default/user.html, views/lti/store.html
* Allows TC to select an assignment !
Problems
=> provide endpoint for lti store

modules/questions_report.py
Correctly use a specific timestamp field if it's available.
=> Fix: Use valid timestamp.

modules/common_builder.py, modules/scheduled_builder.py
A grab-bag of dates/fixes for the LP question type.
=> Lp updates

controllers/admin.py, controllers/ajax.py, models/db_ebook.py, rsmanage/rsmanage.py, tests/conftest.py, tests/test_ajax2.py, tests/test_server.py
The only question is whether we should save anonymous users' data to code?  The only real issue is whether it has research value, and at this point I don't think it really does.
=> acerror_log is redundant - remove all access but not the table just yet.

modules/db_dashboard.py
modified pct calculation to be scaled from 0 to 100 and converted to an int to drop excess precision.
=> modified percentage calculation that appears on progress page

conf.py, controllers/ajax.py, models/grouped_assignments.py, tests/conftest.py
More docs updates -- again, comments welcome!
=> Docs updates

controllers/admin.py, controllers/assignments.py, modules/rs_grading.py, static/js/admin.js, tests/test_admin.py, views/admin/assignments.html, views/assignments/doAssignment.html
The search interface allows one to find questions outside of the current base course.  However several steps were missing in integrating these questions into an assignment.  This PR fixes that.
=> Cross course qs

tests/conftest.py, tests/test_course_1/_sources/index.rst, tests/test_course_1/_sources/selectquestion.rst, tests/test_runestone_components.py
Add tests for the clickable area Runestone component, both plain and in a selectquestion.
DRY the testing approach.
This complements https://github.com/RunestoneInteractive/RunestoneComponents/pull/1165.
=> Clickable area server-side tests

controllers/admin.py, static/js/admin.js, views/admin/assignments.html
Addressing https://github.com/RunestoneInteractive/RunestoneServer/issues/1613 "I would like the ability to copy an assignment from the same course"
**Changes made to:**
assignments.html 
- Added a form group to the 'Add' modal window to provide the option of creating a new assignment that copies the settings, readings, and questions from an existing assignment
admin.js
- Added function `duplicateAssignmentsList` that updates the Duplicate From dropdown list to match the list of existing assignments
- Updated function `createAssignment` with a condition to check whether the newly created assignment is intended to be a copy, and if so then retrieve the data of the source assignment and set the data of the newly created assignment to match. …
=> Duplicate an assignment

tests/conftest.py, tests/test_course_1/_sources/index.rst, tests/test_course_1/_sources/selectquestion.rst, tests/test_runestone_components.py
Testing for https://github.com/RunestoneInteractive/RunestoneComponents/pull/1171.
=> Add: Port mchoice tests, plus revise test framework.

controllers/ajax.py, modules/feedback.py, tests/test_ajax2.py, tests/test_autograder.py, tests/test_course_1/_sources/index.rst, tests/test_course_1/_sources/selectquestion.rst, tests/test_runestone_components.py
Fixes fitb percent correct calculation for server-side grading as well.
=> More tests

tests/test_course_1/_sources/activecode.rst, tests/test_course_1/_sources/index.rst, tests/test_course_1/_sources/selectquestion.rst, tests/test_runestone_components.py
This will fail until https://github.com/RunestoneInteractive/RunestoneComponents/pull/1175 is merged.
=> Add: activecode test.

.github/workflows/python-app.yml, static/js/admin.js, tests/test_server.py, views/_sphinx_static_files.html
I couldn't figure out how to revise/push to #1655, so I'm opening this instead. This ended up being a smorgasboard of fixes to work around several existing problems:
- The sphinx template html code was being included twice, because the syntax of some templates was wrong. I fixed the syntax plus indented the code to make the flow of the templates clearer.
- The selectquestion test fails, because mathjax isn't included by Sphinx on that page, since it doesn't have math. As a workaround, I added an equation to the page. However, this is a fundamental problem with selectquestion and Sphinx.
=> Runestone bundle server

.github/workflows/python-app.yml
This reverts commit c5a8c27f84760a4b908d2005ed5149a6287d8848.
=> Revert "DELETE ME: Run tests against newest components."

controllers/ajax.py
In conjunction with https://github.com/RunestoneInteractive/RunestoneComponents/pull/1189
=> Update ajax.py for select toggle changes

views/assignments/doAssignment.html
In conjunction with https://github.com/RunestoneInteractive/RunestoneComponents/pull/1206
=> For parsons distractor helptext

views/admin/admin.html
Addressing #1705 
Went with suggested approach of changing to 'Chapter Activity' in place of Chapter Progress
=> Making Chapter Activity & Progress Buttons Match

views/default/user.html, views/layout.html
=> Fix: Don't show scratch activecode in the user view, since RS components aren't loaded there.

models/0.py, models/db.py, models/db_ebook.py, models/db_ebook_chapters.py, models/grouped_assignments.py, models/lti.py, models/questions.py, rsmanage/initialize_tables.py
Fixes (plus one DELME) to get web2py playing nicely with the bookserver.
=> Db to bookserver

controllers/default.py, tests/conftest.py, tests/test_server.py
Fix: If a student already owns a course, then any courses from the same base course are free.
=> Payment fix

Dockerfile, docker-compose.yml, docker/README.rst, docker/docker_tools.py, docker/docker_tools_misc.py, docker/nginx/sites-available/runestone
Also, lots of docs updates.
I don't have a great way to test this -- please help!
=> Fix: Correct certbot setup.

controllers/default.py, controllers/lti.py, models/db.py
=> Fix: LTI needs JWT token.

docs/lti.rst
Eliminated CS Awesome server's URL
=> Update LTI launch URL

controllers/lti.py
Guess at correct name for user object.
=> Fix: Add missing JWT token generation.

rsmanage/rsmanage.py
=> Fix: Clean up flags for rsmanage addcourse.

models/db.py
=> Fix: Correct course routing. Always use the new bookserver.

docker/docker_tools.py
=> Fix: Avoid printing password to stdout.

docker/docker_tools.py
=> Fix: Install libs needed by sim30.

modules/common_builder.py, modules/questions_report.py, modules/scheduled_builder.py
Add: Rust, ARM builder; use runguard.
Works in production.
=> Refactor: A more general builder framework.

controllers/assignments.py, scripts/buildbook
This PR fixes #1765 
We also added documentation to the function get_summary 
Image below shows unsupported types not being linked
We are Berea College students and this pull request was approved by @pearcej
=> Fixes exercisemetrics links 

tests/test_autograder.py, tests/test_dashboard.py, tests/test_designer.py, tests/test_server.py
Otherwise know as, "skip failing tests! Then they pass!" (Although there are also some genuine fixes.)
Fix: Update autograde since an assignment_id is now required for updating a grade.
Get more tests passing.
=> Get testing passing (finally)

static/js/assignment_table.js
This is just VSCode running Prettier on the existing JS. After this is merged, I'll show a few changes I made to fix the assignment table. (Otherwise, the Prettier changes made any "real" diff hard to read.)
=> Clean: Prettier.

rsmanage/rsmanage.py
fetch files for _static folder for pretext deployments to a runestone server.
=> Populate the necessary static files

controllers/assignments.py, docker/docker_tools.py, docker/docker_tools_misc.py, docker/gunicorn_config/fastapi_config.py
* use daemon mode for gunicorn to avoid HUP issues
* add reloadbks command to quickly reload the bookserver
=> Fixes for and efficiency updates

docker/README.rst, docker/docker_tools.py
- Refuse to install Docker under WSL.
- Install tools in venv if it's activated.
- Improve docs.
These fixes come from working with @pearcej on getting Docker working for her students.
=> Improve Docker setup:

.github/workflows/python-app.yml, docker/README.rst, docker/docker_tools.py
Rewrite docs for the Docker build process.
=> Refactor: separate bootstrap from build process for the Docker tools.

.github/workflows/python-app.yml, docker/README.rst, docker/docker_tools.py
Update to docker compose (v2 interface), instead of docker-compose.
=> Fix: Better detection of the Docker Desktop on OS X.

docker/README.rst
=> Docs: Point to PreTeXt author resources.

docker/docker_tools_misc.py, pyproject.toml
=> Add: Send Celery log data to the Docker logs.

docker/docker_tools.py, poetry.lock, pyproject.toml
Update major version of some dev packages.
=> Fix: Add dev path to Runestone Components.

Dockerfile, docker/docker_tools.py, docker/docker_tools_misc.py, docker/gunicorn_config/fastapi_config.py
Before moving Celery stuff around, clean up path to BookServer.
=> Bookserver path

tests/test_course_1/_sources/lp_demo.py
Merging this will make https://github.com/RunestoneInteractive/BookServer/pull/102 pass.
=> Fix: Correct test for newer LP builders.

runestone_poetry_project/poetry_fix.py
Remove unused docs
Docs: Improve.
=> Fix: In poetry_fix, ignore missing poetry.lock

docker/docker_tools_misc.py
Fix: 
- Correct logging destinations.
- Correct Celery startup.
=> Docker fixes -- Celery and logging

docker/docker_tools.py
A few minor tweaks to the Docker setup: replace `apt-get` with `apt` and correctly escape a string.
=> Docker cleanup

docker/docker_tools.py
It amazes me to see what's available in the open-source world. Here's a Verilog simulator, already packaged for Debian. Amazing!
=> Add: Option to install a the Icarus Verilog simulator.

rsmanage/rsmanage.py
Update docs for `adduser` slightly.
Remove debug print statements in `studentinfo`.
=> Rsmanage fixes
