RunestoneInteractive/RunestoneServer

modules/luther/sphinx/activecode/js/activecode.js
This fixes the audio tour creation to index more for line numbers less
than 10 and less than 100.
=> Fix to audio tour due to line numbers

README.rst, models/0.py, modules/chapternames.py, requirements.txt
I found many instances of import subprocess (built-in python module from 2.6 onward). I didn't find any references to subprocess32. 
subprocess32 seems to be deprecated for windows. If it's not truly required, removing this requirement will save some headaches for people installing.
=> removed requirement for subprocess32

controllers/ajax.py, models/db_ebook.py
In the old JS Parsons, the area from which code blocks were dragged, was called trash. In the new versions, it is called source. This updates the database tables to correspond to the change in name.
=> change trash to source in parsons_answers

models/scheduler.py, views/admin/index.html
only pip and thinkcspy have special splash pages with the table of contents moved to toc.rst  This changes the build process to be consistent for all books.  This also requires the pull request in thinkcspy (and @presnick should make a change to pip as well).
=> killing off the toc special case

controllers/default.py, requirements.txt, views/default/reportabug.html, views/groupLayout.html, views/layout.html
I replaced the old problem page that directed the user to go to Github and report an issue there with a new page that, when the form is filled out and submitted, will automatically post a new issue into the the repository of the book that the problem originated in. This will require github credentials to be added into 'default.py'
=> Github API  Bug Reports

views/designer/index.html
There is already a datepicker, but it's attached to a text input box that is still able to be typed in.  I've added an onkeydown='return false' to the cooresponding input tag, and that would solve the problem of users typing in dates, without breaking the datepicker.
=> Have term_start_date input only be determined by datepicker to solve issue #913

views/layout.html
I saw there was another issue similar to this one that has been closed, but I was still unable to reach the help page from the instructor help links in the home page or the instructor interface pages. (The help link did work from the table of contents page though.)
=> fixed instructor help link for home page and instructor pages to solve issue #906

models/db_ebook.py
The format is "0,1,2,3,4,5,...". With a length of 10, this is limited. I'm getting server-side exceptions on some of my (longer) multiple-choice questions.
=> Fix: Allow more than 5 options in a multiple-choice question.

controllers/assignments.py, models/grouped_assignments.py, tests/make_clean_db_with_grades.py, tests/run_tests.sh, tests/test_ajax.py, tests/test_assignments.py
This one should be clean, with no dependence on the lti updates. DB migration required because of addition of deadline field to question_grades, to record what deadline was used in computing the grade.
=> Clean unit test

README.rst
Removed reference to `README_new_book.rst` which is not part of the project anymore. 
Added link to the guide on the RS Components repo.
=> Removed old reference in README, fixed #1078

controllers/assignments.py, scripts/find_modified_index.py, tests/test_assignments.py
This PR eliminates the extremely troublesome chapterSections variable.  The questions table does now include the chapter_label as well as the subchapter label and these are going to be much more reliable than inferring from the name. 
-- This may even fix the problem that occurs when an author does not follow the use of the toctree.rst per chapter pattern.
-- I should add that I wrote a unit test for doAssignment before doing this which passed on the test database and this test continues to pass with the new code in place -- Yay unit tests.
=> eliminate chapterSections variable

views/dashboard/index.html
Per our conversation on Slack, here's a webserver-independent way to specify the gradebook link.
=> Fix: Correctly specify URL for link.

controllers/ajax.py, controllers/coach.py, controllers/default.py, requirements-test.txt, tests/make_clean_db_with_grades.py, tests/run_tests.py, tests/test_ajax.py, tests/test_server.py, views/admin/admin.html, views/admin/diffviewer.html, views/admin/doc.html, views/assignments/chooseAssignment.html, views/assignments/doAssignment.html, views/assignments/index.html, views/assignments/practice.html, views/dashboard/grades.html, views/default/courses.html, views/default/donate.html, views/default/remove.html, views/default/user.html, views/layout.html, views/oauth/index.html
This PR contains a revamped pytest approach with fixtures for most basic operations. In addition:
- A minor tweak to the server to support testing.
- More HTML fixes to pass validation tests.
- Changes to avoid hardcoding the application as 'runestone' where possible. There are still more places where this could be done. I run an exam_runestone application to give tests, which has a different setup than my usual runestone application where I assign homework.
To verify this last change, I ran the tests before commit 35f21a7f5c81f9cc60f85a65e2805c784c3db5fe, then ran them again after that commit and compared differences in the generated HTML based on these additions to `test_server.py` starting at line 189:
``` Python
from difflib import unified_diff
file_name = url.replace('/', '-') + …
```
=> pytest improvements + HTML fixes

tests/test_server.py, views/assignments/practice.html, views/assignments/practiceNotStartedYet.html, views/default/privacy.html, views/default/terms.html, views/default/user.html
This corrects the test failures seen in recent PRs, such as #1159. I'm guessing the W3C validator changed, hence the failures. The changes consist of:
1. Move `<style>` tags into the `<head>` tag (see 96ca8e3ec8ec242bfb1368f2cad0fe6a0653e3bc).
2. Remove duplicate Facebooks scripts, since they're already present in [views\layout.html](https://github.com/RunestoneInteractive/RunestoneServer/blob/master/views/layout.html#L38). See 96ca8e3ec8ec242bfb1368f2cad0fe6a0653e3bc.
3. Update the tests, since this reduces the number of validation errors to ignore. See d65cf686694f5aafc7f6c2ea4ca24acc321ad5bb.
This should be merged before anything else, since otherwise the test suite will report errors unrelated to those PRs.
=> Fix validation

static/js/admin.js
@presnick , @bjones1 
This change was inspired by a hack published by one of our professors.  
It subverts grading ALL problems for ALL students when just the assignment is selected.  The underlying problem is that autograde is too slow for large classes or large assignments, but this gets around the problem by grading one student at a time.
I think its better than letting the majority of users suffer.
Comments?
=> Workaround: Never grade all problems for all students

modules/rs_grading.py
Sometimes, `score` is `None`, causing an exception.
=> Fix: Avoid exception when displaying the gradebook.

tests/test_admin.py, tests/test_dashboard.py
This fixes errors caused when `sys` is used, but never imported.
=> Fix broken tests.

static/js/admin.js, views/admin/grading.html
This uses JavaScript's async capabilities to avoid blocking while performing grading. Without this, my browser (Chrome) freezes while doing grading. It also provide a nice display of what's currently being graded. With 180 students in my course, this is essential.
=> Fix: Display progress while grading without blocking.

models/db.py
This is one more place where we can avoid hard-coding the application name, without changing the behavior of the Runestone server.
=> Fix: Let application name determine masterapp for session storage.

controllers/dashboard.py, requirements-test.txt, requirements.txt, tests/test_dashboard.py, views/dashboard/index.html, views/dashboard/subchapoverview.html
This  is in response to one of the top requested features I get from instructors, more granularity than they get in the student progress page and the ability to download data in a useful form. I think this addresses that without just giving them a dump of the firehose that is useinfo.
It gives them 4 reports
1.  student by subchapter with a count of the number of distinct activities each student has done.
2. student by subchapter-div_id with a timestamp of the first time they interacted with an activity
3. student by subchapter-div_id with a timestamp of the last time they interacted with an activity
5. student by subchapter-div_id with a count of the number of times they interactive with an activity
To anticipate -- I'm thinking about how I would write a unit test for this @bjones1 .
=> Pivot reports

Dockerfile, docker/entrypoint.sh
This is ATM just an initial version of Dockerfile which just installs needed components
Setup
- Have `books/` directory with books (due to #1180 I guess should only be known books)
- Optionally have `configs/{instructors,students}.csv` and bindmount that configs as `/srv/configs` to get DB populated and locked down
- Run docker with needed bind mounts and only a few options (e.g. DB password) to get the whole machinery setup and running
- Running container then should be cherished to not be gone, since it would contain built/deployed books and the active DB (see below may be about bind mounting DB itself)
TODOs
Not sure if I will accomplish all of the above TODOs but want to reach a usable for myself state first to consider it at least "done enough", the rest of non-fulfilled TODOs then …
=> WiP: Dockerfile for turnkey deployments

ChangeLog.rst, Dockerfile, build/preview/conf.py, controllers/coach.py, docker/entrypoint.sh
The work to make (at least the superficial running) work with Python 3 was fairly simple -
1. exporting encoding environment variables supported (see locale -a for the three) so that click didn't bug out.
2. updating the container installs to python3-X
3. Creating a symbolic link from python3 to 2 so "python3" isn't hard coded everywhere.
4. There was one strange error that web2py didn't like having "runestone" at the end. The -X variable is a flag for running with the scheduler, so I'm guessing that wherever the args are ultimately parsed (the gluon thing?) has a difference between Python 2/3. It seems to work okay removing it, so I'll want your feedback on this.
I suspect that the RunestoneInteractive/RunestoneComponents might need work, along with some of the books? I wasn't sure how …
=> Updates for Python 3

Dockerfile, docker-compose.yml, docker/README.md, docker/entrypoint.sh, docker/nginx/sites-available/runestone, docker/systemd/system/uwsgi.service, docker/uwsgi/sites/runestone.ini, docker/wsgihandler.py
These config files are based on the config files from my setup on Digital Ocean running an Ubuntu 16.04 droplet.  This does seem to be compatible with the debian-stretch image that we use as our base.
On digital ocean things are owned and run as the bmiller user.  I've tried to update here to have them owned and run as www-data.
=> config files for uwsgi + nginx

controllers/ajax.py, controllers/designer.py
A couple of minor tweaks. The subtle one I found in testing:
1. A user logs in, does stuff, then logs out.
2. Using the same PC and web browser, another user then hits the `hsblog` endpoint without logging in. Then, the `compareAndUpdateCookieData` function sees the two users as identical. It therefore updates the `useinfo` table with the second user's data, which actually overwrites values the first user submitted. I added an extra check to prevent overwriting a logged-in user with a logged-out user's data.
=> Misc fixes

docker/README.md, docker/entrypoint.sh
Tested on Ubuntu 18. I tested this on a clean VM; these changes allows git operations to work after Docker is running.
=> Fix: Correct Docker permissions.

controllers/dashboard.py, views/dashboard/index.html
Makes the following changes to the dashboard page:
1. Numbers the chapters in the pulldown menu.
2. Adds chapter and section number to the Overall Progression bars
BUG: The section number is incorrect for section names that appear more than once, like Glossary, Exercises, etc. 
3. Separates the "progress rings" by section, sorts numerically by section number, and includes section title.
=> Changes to the Instructor's Dashboard

controllers/admin.py, static/js/admin.js, tests/test_server.py, views/admin/assignments.html
1) Allow instructor to rename Assignments on assignments tab, using a modal dialog that is similar to the createAssignment dialog.
2) Prevent two assignments from having the same name in the same course (either when creating or renaming an assignment).
3) Change the label on the "Close" button on the modal dialogs in the assignments tab to "Cancel", for clarity. (I wasn't sure if Close meant "do this and then close" or "close instead of doing this")
4) Change the + and - buttons to "Add" and "Delete" for clarity (and to match the new "Rename" button).
=> Allow instructor to rename Assignments on assignments tab.

models/db.py, views/dashboard/index.html
Adds a Hide/Show button to the Dashboard Student Activity panel, so that instructors can show the donut graphs to students in class without revealing personal student information.
=> Option to hide the Student Activity panel on Dashboard

views/dashboard/exercisemetrics.html, views/dashboard/grades.html, views/dashboard/index.html
@bnmnetp, do you want this sort of thing fixed? Or is this just annoying?
Doing so shows at least one mis-balanced file (`index.html`) that I don't know how to fix.
IMHO, we should standardize and try to enforce a whitespace policy, especially for web2py templates. Otherwise, they are very hard to read and fix. My proposal:
1. All indents are 4 spaces. Tabs are not allowed.
2. For HTML tags, two styles are supported: `<tag>`Contents`</tag>` (one line) or `<tag>`, then multiple indented lines, then an un-indented `</tag>`.
3. All web2py commands that produce nesting require an indent: `{{ if x: }}`, followed by indented text, then an un-indented `{{ pass }}`.
4. All web2py commands will follow the format: `{{ commands }}`, with one space between the curly braces and the command. For …
=> Whitespace clean

controllers/books.py, models/grouped_assignments.py, rsmanage/grade.py
This removes unused imports, and add a missing `import datetime` in books.py to help avoid web2py bugs associated with its weird import system.
=> Fix: Import datetime and use it consistently.

static/js/selfgrade.js
/assignments/student_autograde doesn't look at enforceDeadline, so it's misleading to have it set here.
=> clean up selfgrade.js

controllers/ajax.py, controllers/books.py
This addresses issues where the session cookie times out but the page is not reloaded.  So the eBookConfig.isLoggedIn value is true, but the session cookie has expired.
This also addresses the issue where you have multiple tabs open and change courses in one tab but come back to a previous tab.  Now your current course for the session does not match the course of the book you are displaying.
This also restores the commented out functionality of the idle timer reloading the page, which does seem to work nicely and forces the user to login again when the session expires.
This needs the support of the companion PR on RunestoneComponents
@bjones1 - The most confusing case is when a student logs in to course "babyfopp" a child course of fopp.  Then makes a bookmark -- But the bookmarked url is …
=> plug holes in session expirations

controllers/admin.py, tests/test_admin.py
This commit adds unit tests for the edit_question endpoint in admin.py, in reference to #1070 and #1259 
In order to create tests in line with other tests in the suite, edit_question needed to be modified to add `json.dumps()` calls surrounding all outputs. As otherwise `json.loads()` would fail on the test.
This change only applies to edit_question and should not affect the usage of the interface.
=> Added tests for edit_question endpoint

controllers/default.py, rsmanage/rsmanager.py, tests/test_server.py
Users were reporting a 502 gateway timeout when trying to use the self deletion option.
Investigation showed that deleting entries from useinfo and acerror_log is VERY slow due to constraint enforcement.
This does most of the work in the background.
=> deleting a user takes a LONG time do it in the bg

models/db.py
This helps with annoying tools like Cisco's link renamer, which breaks URLs in Runestone password reset e-mail that are sent as plain text.
=> Fix: Generate HTML when sending a password reset e-mail.

controllers/books.py
The message "You Most likely want to log in to access your course" was fixed to lowercase the "Most" in the sentence in the login page.
=> Fix typo in login page

docker/entrypoint.sh
Added 2 commands to prevent the missing logs error upon boot-up to fix issue #1417
=> Inserted Booting Log Bugfix #1417

modules/rs_grading.py
Several calls to `logger.debug` didn't provide substitution references, causing exceptions. See the [docs](https://docs.python.org/3.8/library/logging.html#logging.Logger.debug) for the correct syntax. For example, `logger.debug("WTG = ", which_to_grade)` should be `logger.debug("WTG = %s", which_to_grade)`.
=> Fix: Correct logging.

.travis.yml, controllers/ajax.py, controllers/assignments.py, controllers/dashboard.py, controllers/default.py, controllers/designer.py, docker/entrypoint.sh, models/db.py, models/db_ebook_chapters.py, modules/db_dashboard.py, rsmanage/initialize_tables.py, static/js/admin.js, static/motd.html, tests/conftest.py, tests/test_ajax2.py, views/admin/admin.html, views/default/wisp.html
This PR fixes a longstanding annoyance that the chapter progress buttons on the pages as well as the icons in the table of contents will reflect ANY book with that sub_chapter_label.  So a student could start a course in the basecourse and then switch to their instructors course and it would look like they had completed the chapter in the instructors course.  But they would not get credit because the work was done in another course.
This makes the buttons and the icons only reflect work done in the current course so it is consistent with the grader.
=> Progress course only

static/js/admin.js, views/admin/assignments.html
Duplicate the total points that is near the top of the instructors' assignments admin page and places this copy at the bottom of the questions list. This is so that changes to the total points of an assignment can be more easily seen while making changes to an assignment's question list without needing to scroll back up to the top of the page.
See https://github.com/RunestoneInteractive/RunestoneComponents/issues/1143
=> Add total points to bottom of questions list

tests/test_runestone_components.py
Testing for https://github.com/RunestoneInteractive/RunestoneComponents/pull/1167.
=> Add: testing for the Runestone components.

static/js/admin.js, views/admin/assignments.html
Addressing https://github.com/RunestoneInteractive/RunestoneServer/issues/1628 Sort the assignment alphabetically in the drop down list on the assignments page in the instructor's interface
Reorder the options in the assignment list select dropdown alphabetically while preserving their assignment ID and data. This is only meant to be a temporary quick fix that will be replaced by a better longer term solution.
=> Sort assignments list alphabetically in instructor's admin interface (quick fix temporary solution)

.github/workflows/python-app.yml, docker/docker_tools.py, docker/docker_tools_misc.py
Fix: Allow ensure_in_docker to run any program in the Docker venv path, not just docker-tools.
Black cleanup
=> Better `ensure_in_docker`

docker/docker_tools.py
Clean: Remove unused vars, imports.
Works in production.
=> Fix: Remove backport repo after install.

controllers/assignments.py, static/js/admin.js
@sreynit02 and I solved the issue #1763 making the following changes:
1. Pass assignment id with POST data object in admin.js
2. Validate new "assignmentid" parameter for the record_grade function
3. Gather assignment information
4. Call do_calculate_totals() in the record_grade function
This pull request was approved by Dr. Jan Pearce of Berea College.
**Screenshot walkthrough of the change**
The gradebook before instructor changes grade for assignment question:
Question drilldown:
Change point for first question from 0 to 1:
Point is updated in the question drilldown:
Now, the change to question points is also reflected in the gradebook (used to be 50%, now it's 100%, as expected):
=> solve issue #1763 (update total point in gradebook dashboard)

views/default/courses.html
Could not find the `Add Another Course` button.  New instructions worked better for me.
=> Match additional enrollment instructions with button text

docker/docker_tools.py
Fixes [#106](https://github.com/RunestoneInteractive/BookServer/issues/106).
=> Fix: Set up Alembic to allow migrations by stamping the db on creation.

docker/README.rst, docker/docker_tools.py
This puts all the cloned repos in the `rsdocker/` subdirectory.
On OS X, it runs everything in a venv placed in `rsdocker/rsvenv`.
There are also lots of docs fixes and improvements.
=> Fix: Simplify the user-facing install process

views/admin/admin.html
solved issue #1955  By sorting the instructors' and Ta's names in place based on their last names. 
I assumed that each name is made of a first name and the last name, separated by a space. The way the `instructors` dict is built inside admin.py made me assume this should be valid.
=> Sorted the list of instructor in-place inside the admin.html file

docker/docker_tools_misc.py
The `ensure_in_docker()` function already runs `source $RUNESTONE_PATH/.venv/bin/activate`, so we're already in a venv without running `poetry run bash`.
=> Clean: Remove unnecessary shell --venv option.

docker/.env.prototype, docker/README.rst, docker/__init__.py, docker/docker_tools.py, docker/setup.py, pyproject.toml, rsmanage/setup.py, runestone_poetry_project/poetry_fix.py, tests/conftest.py
This implements ideas in #2048. Not much testing yet.
Fix: 
- auto-edit .env based on the build type.
- Links development-only files only in dev mode.
Docs: 
- Improve docs on .env.prototype
=> Improve docker-tools for `build --single`

docker/gunicorn_config/fastapi_config.py, docker/gunicorn_config/web2py_config.py
Launching large numbers of workers causes issues on high core count machines when developing in WSL
=> Reduce worker count on development deploys
